# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Lint

on:
  push:
    branches:
    - "**"

jobs:
  verify:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v4

    - name: Extract python version from Pipfile.lock
      id: get-python-version
      run: echo "python_version=$(jq -r '._meta.requires.python_full_version' Pipfile.lock || echo '')" >> $GITHUB_OUTPUT

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ steps.get-python-version.outputs.python_version }}
        cache: 'pipenv'
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Install dependencies
      run: pipenv sync --dev

    - name: Lint
      run: pipenv run lint
